[package]
name = "laplace_rs"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"
statrs = "0.16.0"
rand = "0.8.5"
anyhow = "1.0.69"
