name: Rust housekeeping

on:
  push:
  pull_request:
  schedule:
    # Fetch new base image updates every night at 1am
    - cron: '0 1 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-check:
    name: Security, License Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1

  check:
    name: Rust tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust" # Increase to invalidate old caches.
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
